name: ğŸ”Œ CI - Testes de API (Node.js)

on:
  push:
    branches: [ main ]
    paths:
      # Roda a pipeline somente se houver mudanÃ§as na pasta 'api' ou no prÃ³prio workflow
      - 'api/**'
      - '.github/workflows/api_ci.yml'

jobs:
  run_api_tests:
    runs-on: ubuntu-latest
    steps:
      - name: â¬‡ï¸ Checkout do CÃ³digo
        uses: actions/checkout@v4

      - name: âš™ï¸ Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: ğŸ“¦ Instalar DependÃªncias (API)
        # Garante que o npm install rode dentro da subpasta 'api'
        run: npm install
        working-directory: api

      - name: ğŸƒ Rodar Testes de API
        # Garante que o npm test rode dentro da subpasta 'api'
        run: npm test
        working-directory: api