name: ğŸ¤– CI - Testes BDD CodeceptJS

on:
  push:
    branches: [ main ]
    paths:
      # Roda a pipeline somente se houver mudanÃ§as na pasta 'codeceptjs' ou no prÃ³prio workflow
      - 'codeceptjs/**'
      - '.github/workflows/codeceptjs_ci.yml'

jobs:
  run_node_tests:
    runs-on: ubuntu-latest
    steps:
      - name: â¬‡ï¸ Checkout do CÃ³digo
        uses: actions/checkout@v4
        
      - name: âš™ï¸ Configurar Node.js (v20)
        uses: actions/setup-node@v4
        with:
          node-version: 20
          
      - name: ğŸ“¦ Instalar DependÃªncias (CodeceptJS)
        # Garante que o npm install rode dentro da subpasta 'codeceptjs'
        run: npm install
        working-directory: codeceptjs
        
      - name: ğŸƒ Rodar Testes CodeceptJS
        # Comando correto para execuÃ§Ã£o do CodeceptJS
        run: npx codeceptjs run --steps
        working-directory: codeceptjs