name: И CI - Testes E2E Cypress

on:
  push:
    branches: [ main ]
    paths:
      # Roda a pipeline somente se houver mudan莽as na pasta 'cypress' ou no pr贸prio workflow
      - 'cypress/**'
      - '.github/workflows/cypress_ci.yml'

jobs:
  run_cypress_tests:
    runs-on: ubuntu-latest
    steps:
      - name: 猬锔 Checkout do C贸digo
        uses: actions/checkout@v4

      - name: 锔 Configurar Node.js (v20)
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name:  Instalar Depend锚ncias
        # Garante que o npm install rode dentro da subpasta 'cypress'
        run: npm install
        working-directory: cypress

      - name:  Rodar Testes Cypress (Headless)
        # Executa os testes no modo Headless
        run: npx cypress run
        working-directory: cypress

      - name: 猬锔 Publicar Relat贸rios (Artefatos)
        # Opcional, mas altamente recomendado: salva v铆deos, screenshots e relat贸rios
        if: always() # Roda mesmo se a etapa de teste falhar
        uses: actions/upload-artifact@v4
        with:
          name: cypress-results
          path: cypress/reports # Ajuste o caminho conforme a sua pasta de relat贸rios