name: ğŸ“Š CI - Scripts k6 (Performance)

on:
  push:
    branches: [ main ]
    paths:
      - 'k6/**'
      - '.github/workflows/k6_ci.yml'

jobs:
  run_k6_smoke_test:
    runs-on: ubuntu-latest
    steps:
      - name: â¬‡ï¸ Checkout do CÃ³digo
        uses: actions/checkout@v4

      - name: ğŸ§ª Instala k6 Manualmente (Contorno de Action)
        run: sudo snap install k6

      - name: ğŸƒ Rodar Teste de FumaÃ§a (Smoke Test)
        run: /snap/bin/k6 run script.js
        working-directory: k6