name: ğŸ“Š CI - Scripts k6 (Performance)

on:
  push:
    branches: [ main ]
    paths:
      - 'k6/**'
      - '.github/workflows/k6_ci.yml'

jobs:
  run_k6_smoke_test:
    runs-on: ubuntu-latest
    steps:
      - name: â¬‡ï¸ Checkout do CÃ³digo
        uses: actions/checkout@v4

      - name: âš™ï¸ Configurar k6
        uses: grafana/k6-action@v1.0.0
        with:
          k6-version: 'latest'

      - name: ğŸƒ Rodar Teste de FumaÃ§a (Smoke Test)
        run: k6 run script.js --vus 1 --iterations 10
        working-directory: k6