name: ğŸ“Š CI - Scripts k6 (Performance)

on:
  push:
    branches: [ main ]
    paths:
      - 'k6/**'
      - '.github/workflows/k6_ci.yml'

jobs:
  run_k6_smoke_test:
    runs-on: ubuntu-latest
    steps:
      - name: â¬‡ï¸ Checkout do CÃ³digo
        uses: actions/checkout@v4

      - name: ğŸ§ª Instala k6 Manualmente (Contorno de Action)
        run: |
          sudo apt-get install -yq --no-install-suggests --no-install-recommends ca-certificates curl
          curl https://keybase.io/grafana/key.asc | sudo gpg --dearmor -o /usr/share/keyrings/grafana.gpg
          echo "deb [signed-by=/usr/share/keyrings/grafana.gpg] https://apt.grafana.com stable main" | sudo tee /etc/apt/sources.list.d/grafana.list
          sudo apt-get update
          sudo apt-get install k6

      - name: ğŸƒ Rodar Teste de FumaÃ§a (Smoke Test)
        run: k6 run script.js
        working-directory: k6