name: ğŸ“Š CI - Scripts k6 (Performance)

on:
  push:
    branches: [ main ]
    paths:
      - 'k6/**'
      - '.github/workflows/k6_ci.yml'

jobs:
  run_k6_smoke_test:
    runs-on: ubuntu-latest
    steps:
      - name: â¬‡ï¸ Checkout do CÃ³digo
        uses: actions/checkout@v4

      - name: ğŸ§ª Instala k6 Manualmente (Contorno de Action)
        run: |
          sudo apt-get install -yq ca-certificates curl gnupg
          sudo mkdir -p /etc/apt/keyrings
          curl -1sLf "https://dl.k6.io/keybase.gpg" | sudo gpg --dearmor -o /etc/apt/keyrings/k6-archive-keyring.gpg
          echo "deb [signed-by=/etc/apt/keyrings/k6-archive-keyring.gpg] https://dl.k6.io/deb stable main" | sudo tee /etc/apt/sources.list.d/k6.list
          sudo apt-get update
          sudo apt-get install k6

      - name: ğŸƒ Rodar Teste de FumaÃ§a (Smoke Test)
        run: k6 run script.js
        working-directory: k6