name: ğŸ CI - Testes Python (Pytest)

on:
  push:
    branches: [ main ]
    paths:
      # Roda a pipeline somente se houver mudanÃ§as na pasta 'python' ou no prÃ³prio workflow
      - 'python/**'
      - '.github/workflows/python_ci.yml'

jobs:
  run_pytest:
    runs-on: ubuntu-latest
    steps:
      - name: â¬‡ï¸ Checkout do CÃ³digo
        uses: actions/checkout@v4

      - name: ğŸ Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          # Adiciona o cache de pacotes Python para builds mais rÃ¡pidos
          cache: 'pip' 

      - name: ğŸ“¦ Instalar DependÃªncias
        # Garante que o pip esteja atualizado e instala as dependÃªncias do projeto
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        working-directory: python

      - name: ğŸƒ Rodar Testes com Pytest
        # Executa a suÃ­te de testes Pytest na pasta 'python'
        run: pytest
        working-directory: python