name: ğŸ CI - Testes Python (Pytest)

on:
  push:
    branches: [ main ]
    paths:
      - 'python/**'
      - '.github/workflows/python_ci.yml'

jobs:
  build_and_test_java:
    runs-on: ubuntu-latest
    steps:
      - name: â¬‡ï¸ Checkout do CÃ³digo
        uses: actions/checkout@v4

      - name: â˜• Configurar Java (v17)
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven' # Mude para 'gradle' se usar Gradle

      - name: ğŸ—ï¸ Compilar e Rodar Testes com Maven
        # Ajuste este comando (mvn test ou mvn clean install) conforme o seu build
        run: mvn test
        working-directory: python