name: â™¦ï¸ CI - Testes Ruby (RSpec)

on:
  push:
    branches: [ main ]
    paths:
      # Roda a pipeline somente se houver mudanÃ§as na pasta 'ruby' ou no prÃ³prio workflow
      - 'ruby/**'
      - '.github/workflows/ruby_ci.yml'

jobs:
  run_rspec_tests:
    runs-on: ubuntu-latest
    steps:
      - name: â¬‡ï¸ Checkout do CÃ³digo
        uses: actions/checkout@v4

      - name: â™¦ï¸ Configurar Ruby
        # Configura o ambiente Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1' # VersÃ£o recomendada para CI
          bundler-cache: true # Usa o cache de Bundler para acelerar o 'bundle install'
        working-directory: ruby

      - name: ğŸƒ Rodar Testes com RSpec
        # Executa os testes usando o RSpec via Bundler
        run: bundle exec rspec
        working-directory: ruby