name: â™¦ï¸ CI - Testes Ruby (RSpec)

on:
  push:
    branches: [ main ]
    paths:
      - 'ruby/**'
      - '.github/workflows/ruby_ci.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'ruby/**'
      - '.github/workflows/ruby_ci.yml'

jobs:
  run_rspec_tests:
    runs-on: ubuntu-latest
    steps:
      - name: â¬‡ï¸ Checkout do CÃ³digo
        uses: actions/checkout@v4

      - name: â™¦ï¸ Configurar Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'

      - name: ğŸ“¦ Instala DependÃªncias (Bundle Install)
        run: bundle install 
        working-directory: ruby

      - name: ğŸƒ Rodar Testes Ruby (RSpec/Cucumber)
        run: bundle exec rspec spec/
        working-directory: ruby