name: ğŸ”Œ CI - Testes de API Supertest

on:
  push:
    branches: [ main ]
    paths:
      # Roda a pipeline somente se houver mudanÃ§as na pasta 'supertest' ou no prÃ³prio workflow
      - 'supertest/**'
      - '.github/workflows/supertest_ci.yml'

jobs:
  run_node_tests:
    runs-on: ubuntu-latest
    steps:
      - name: â¬‡ï¸ Checkout do CÃ³digo
        uses: actions/checkout@v4
        
      - name: âš™ï¸ Configurar Node.js (v20)
        uses: actions/setup-node@v4
        with:
          node-version: 20
          
      - name: ğŸ“¦ Instalar DependÃªncias (Supertest)
        # Garante que o npm install rode dentro da subpasta 'supertest'
        run: npm install
        working-directory: supertest
        
      - name: ğŸƒ Rodar Testes Supertest
        # Supertest Ã© tipicamente executado via o script 'test' do package.json
        run: npm test
        working-directory: supertest