name: â˜• CI - Testes E2E TestCafe

on:
  push:
    branches: [ main ]
    paths:
      - 'testcafe/**'
      - '.github/workflows/testcafe_ci.yml

jobs:
  run_node_tests: # Mantenha o nome do job genÃ©rico se quiser
    runs-on: ubuntu-latest
    steps:
      - name: â¬‡ï¸ Checkout do CÃ³digo
        uses: actions/checkout@v4
      - name: âš™ï¸ Configurar Node.js (v20)
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: ğŸ“¦ Instalar DependÃªncias
        run: npm install
        working-directory: testcafe
      - name: ğŸƒ Rodar Testes
        # Use o comando apropriado (npx cypress run, npx playwright test, npm test, etc.)
        run: npx cypress run
        working-directory: testcafe